#Config file for the ASM part of GTNHCoreMod
#Tue Jul 28 12:17:03 CEST 2026
downloadOnlyOnce=true
patchItemFocusWarding=true
showConfirmExitWindow=false
displayedModpackVersion=2.9.x (Daily 657) - 2026-08-02
